version: '3'

services:

  pg_db:
    image: postgres
    hostname: pg_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=1111
      - POSTGRES_USER=postgres
      - POSTGRES_DB=weather
    volumes:
      - app_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  app_db: {}
