# Generated by Django 3.2.6 on 2021-08-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название города')),
                ('temp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Температура')),
            ],
        ),
    ]
