# Generated by Django 3.2.6 on 2021-08-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_remove_city_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='temp',
            field=models.DecimalField(blank=True, decimal_places=2, default='1', max_digits=5, verbose_name='Температура'),
        ),
    ]
